name: desk_switch
description: "A cross-platform KVM (Keyboard, Video, Mouse) switch application, built with Flutter. Allows users to control multiple computers using a single keyboard, mouse, and monitor setup."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1
  flutter: ">=3.32.0"

platforms:
  macos:
  windows:

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State management and UI
  hooks_riverpod: ^3.0.0-dev.15
  flutter_hooks:
  riverpod_annotation: ^3.0.0-dev.15
  go_router: ^15.1.3

  # Code generation
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  # Platform-specific functionality
  window_manager: ^0.5.0
  desktop_window: ^0.4.2
  permission_handler: ^12.0.0
  device_info_plus: ^11.4.0
  platform: ^3.1.6

  # Network communication
  socket_io_client: ^3.1.2
  network_info_plus: ^6.1.4
  web_socket_channel: ^3.0.3
  bonsoir: ^5.1.11

  # Utilities
  shared_preferences: ^2.5.3
  logger: ^2.5.0
  path_provider: ^2.1.5
  uuid: ^4.5.1
  intl: ^0.20.2
  gap: ^3.0.1
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  custom_lint:
  riverpod_lint: ^3.0.0-dev.15
  build_runner: ^2.4.15
  mockito: ^5.4.6
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  riverpod_generator: ^3.0.0-dev.15

flutter:
  uses-material-design: true
  generate: true

  # assets:
  #   - assets/images/
  #   - assets/icons/
